// Generated by CoffeeScript 1.6.2
(function() {
  (typeof exports !== "undefined" && exports !== null ? exports : this).Blog = (function() {
    var init;

    init = function() {
      return $.get('blog/1000GoodIntentions.html', (function(result) {
        $('#content-blog').html(result);
        $('#blog a').attr('target', '_blank');
        $('#cover-blog img').attr('src', '../blog/covers/LA DISPUTE - WILDLIFE.png');
        return $('#info-blog a').text('LA DISPUTE: Wildlife').attr('href', 'https://itunes.apple.com/nz/album/wildlife/id463651346');
      }));
    };
    return {
      init: init
    };
  })();

}).call(this);
