// Generated by CoffeeScript 1.6.2
(function() {
  (typeof exports !== "undefined" && exports !== null ? exports : this).Colours = (function() {
    return {
      "default": 0xDDDDFF,
      blue: 0x444499,
      white: 0xFFFFFF,
      background: {
        day: 0x000000,
        night: 0x060708
      },
      light: {
        day: 0xDDDDDD,
        night: 0xFFFFFF
      }
    };
  })();

}).call(this);
