// Generated by CoffeeScript 1.6.2
(function() {
  (typeof exports !== "undefined" && exports !== null ? exports : this).CV = (function() {
    var init;

    init = function() {
      return $.get('cv/cv.html', (function(result) {
        $('#content-cv').html(result);
        return $('#cv a').attr('target', '_blank');
      }));
    };
    return {
      init: init
    };
  })();

}).call(this);
