// Generated by CoffeeScript 1.6.2
(function() {
  (typeof exports !== "undefined" && exports !== null ? exports : this).DeviceOrientation = (function() {
    var DEVICE_ORIENTATION, X_AXIS, Z_AXIS, init, piOver540, rotateAroundWorldAxis, _lastBeta, _lastGamma;

    DEVICE_ORIENTATION = 'deviceorientation';
    X_AXIS = new THREE.Vector3(1, 0, 0);
    Z_AXIS = new THREE.Vector3(0, 0, 1);
    piOver540 = Math.PI / 540;
    _lastBeta = _lastGamma = null;
    rotateAroundWorldAxis = function(object, axis, radians) {
      var rotationMatrix;

      rotationMatrix = new THREE.Matrix4();
      rotationMatrix.makeRotationAxis(axis, radians);
      if (axis !== X_AXIS) {
        rotationMatrix.multiply(object.matrix);
      }
      object.matrix = rotationMatrix;
      return object.rotation.setFromRotationMatrix(object.matrix);
    };
    init = function() {
      if (Modernizr.deviceorientation) {
        return window.addEventListener(DEVICE_ORIENTATION, function(event, xTilt, zTilt) {
          if (xTilt == null) {
            xTilt = 0;
          }
          if (zTilt == null) {
            zTilt = 0;
          }
          return _.each(Blocks.common.HEADER.blocks, function(block) {
            if (Math.abs(_lastBeta - event.beta) > 5) {
              xTilt = -event.beta * piOver540;
            }
            if (Math.abs(_lastGamma - event.gamma) > 5) {
              zTilt = event.gamma * piOver540;
            }
            rotateAroundWorldAxis(block.object, X_AXIS, xTilt);
            return rotateAroundWorldAxis(block.object, Z_AXIS, zTilt);
          });
        });
      }
    };
    return {
      init: init
    };
  })();

}).call(this);
