// Generated by CoffeeScript 1.3.3
(function() {
  var clear, load;

  clear = {
    projects: function(callback) {
      return $('.project').animate({
        left: -2000
      }).promise().done(callback);
    }
  };

  load = {
    tuner: function() {},
    transcribe: function() {},
    quantum: function() {}
  };

  $(function() {
    $('.project').removeClass('offscreen');
    return $('.project').click(function() {
      return clear.projects(load[$(this).attr('title')]);
    });
  });

}).call(this);
