// Generated by CoffeeScript 1.3.3
(function() {
  var clear, load, show;

  clear = {
    projects: function(callback) {
      return $('.project').animate({
        left: -2000
      }).promise().done(callback);
    }
  };

  show = {
    projects: function() {
      return $('.project').removeClass('offLeft');
    }
  };

  load = {
    tuner: function() {
      return Tuner();
    },
    transcribe: function() {},
    quantum: function() {}
  };

  $(function() {
    show.projects();
    return $('.project').click(function() {
      return clear.projects(load[$(this).attr('title')]);
    });
  });

}).call(this);
