// Generated by CoffeeScript 1.3.3
(function() {
  var clear, load, show;

  clear = {
    projects: function(callback) {
      $('header').removeClass('active');
      return $('.project').addClass('offLeft').promise().done(function() {
        callback();
        $('.project').removeClass('offLeft').addClass('spinLeft');
        return $('.back').show(function() {
          return $('.back').removeClass('offLeft');
        });
      });
    },
    displays: function() {
      $('.display').addClass('offRight');
      return $('.back').addClass('offLeft').promise().done(function() {
        $('.back').hide();
        return window.location.href = 'http://phenomnomnominal.github.com/';
      });
    }
  };

  show = {
    projects: function() {
      return $('.project').show(function() {
        return $('.project').removeClass('spinLeft');
      });
    }
  };

  load = {
    tuner: function() {
      return $('.tuner').show(function() {
        $('.tuner').removeClass('offRight');
        $('.tuner header').addClass('active');
        return Tuner();
      });
    },
    tetris: function() {
      return $('.tetris').show(function() {
        $('.tetris').removeClass('offRight');
        $('.tetris header').addClass('active');
        return Tetris();
      });
    }
  };

  $(function() {
    show.projects();
    $(window).scroll(function() {
      var scrollAnchor;
      scrollAnchor = $('.scrollAnchor').offset().top;
      if ($(this).scrollTop() >= scrollAnchor && $('.active').css('position') !== 'fixed') {
        $('.scrollAnchor').css('height', $('.active h2').outerHeight());
        $('.back').removeClass('animate').addClass('topHeader');
        return $('.active').addClass('topHeader');
      } else if ($(this).scrollTop() < scrollAnchor && $('.active').css('position') !== 'relative') {
        $('.scrollAnchor').css('height', '0px');
        $('.back').removeClass('topHeader');
        return $('.active').removeClass('topHeader');
      }
    });
    $('.project').click(function() {
      return clear.projects(load[$(this).attr('id')]);
    });
    return $('.back').click(function() {
      clear.displays();
      return show.projects();
    });
  });

}).call(this);
