// Generated by CoffeeScript 1.6.2
(function() {
  (typeof exports !== "undefined" && exports !== null ? exports : this).Materials = (function() {
    var _make;

    _make = function(type, colour) {
      var options;

      options = {
        color: colour,
        shading: THREE.SmoothShading,
        overdraw: true,
        wireframe: Main.debug
      };
      return new THREE["Mesh" + type + "Material"](options);
    };
    return {
      phong: function(colour) {
        return _make('Phong', colour);
      },
      lambert: function(colour) {
        return _make('Lambert', colour);
      }
    };
  })();

}).call(this);
