// Generated by CoffeeScript 1.6.2
(function() {
  (typeof exports !== "undefined" && exports !== null ? exports : this).Projects = (function() {
    var init, kill, update, _currentProject;

    _currentProject = null;
    init = function(project) {
      return $.getScript("/javascript/" + project + ".js").done(function() {
        Rendering.initProject();
        _currentProject = project;
        return window[_currentProject].init($('#project-content'));
      });
    };
    update = function() {
      if (_currentProject) {
        return window[_currentProject].update();
      }
    };
    kill = function() {
      if (_currentProject) {
        window[_currentProject].kill();
        _currentProject = null;
        return Rendering.killProject();
      }
    };
    return {
      init: init,
      update: update,
      kill: kill
    };
  })();

}).call(this);
