// Generated by CoffeeScript 1.6.2
(function() {
  (typeof exports !== "undefined" && exports !== null ? exports : this).Routing = (function() {
    var back, go, init, _currentSection, _router, _setCurrentSection;

    _router = new Router();
    _currentSection = 'home';
    _setCurrentSection = function(newSection) {
      _currentSection = newSection;
      document.title = "Craig Spence | " + (_currentSection.toUpperCase());
      return $('section').removeClass('current').filter("#" + _currentSection).addClass('current');
    };
    init = function() {
      var key, param, params, redirect, value, _i, _len, _ref;

      _router.route('/*path', function() {
        return Projects.kill();
      });
      _router.route('/home', function() {
        return Scenes.change('home', function() {
          return _setCurrentSection('home');
        });
      });
      _router.route('/projects', function() {
        return Scenes.change('projects', function() {
          return _setCurrentSection('projects');
        });
      });
      _router.route('/projects/:project', function(project) {
        Scenes['projects/project'].blockGroups[4] = Blocks.makeProjectTitle(project);
        return Scenes.change('projects/project', function() {
          _setCurrentSection('project');
          return Projects.init(project);
        });
      });
      _router.route('/social', function() {
        return Scenes.change('social', function() {
          return _setCurrentSection('social');
        });
      });
      _router.route('/blog', function() {
        return Scenes.change('blog', function() {
          return _setCurrentSection('blog');
        });
      });
      _router.route('/cv', function() {
        return Scenes.change('cv', function() {
          return _setCurrentSection('cv');
        });
      });
      params = window.location.search.substring(1).split('&');
      for (_i = 0, _len = params.length; _i < _len; _i++) {
        param = params[_i];
        _ref = param.split('='), key = _ref[0], value = _ref[1];
        if (key === 'redirect') {
          redirect = decodeURIComponent(value);
        }
      }
      if (redirect == null) {
        redirect = 'home';
      }
      if (redirect.substr(-1) === '/') {
        redirect = redirect.substr(0, redirect.length - 1);
      }
      if (redirect.substr(0, 1) === '/') {
        redirect = redirect.substr(1);
      }
      return Routing.go(redirect, true);
    };
    go = function(name, replace) {
      if (replace == null) {
        replace = false;
      }
      return _router.navigate("/" + (name.toLowerCase()), true, replace);
    };
    back = function() {
      if (_currentSection === 'projects' || _currentSection === 'social' || _currentSection === 'blog' || _currentSection === 'cv') {
        _router.navigate('/home');
      }
      if (_currentSection === 'project') {
        return _router.navigate('/projects');
      }
    };
    return {
      init: init,
      go: go,
      back: back
    };
  })();

}).call(this);
