// Generated by CoffeeScript 1.6.2
(function() {
  (function() {
    window.requestAnimFrame = (function() {
      return requestAnimationFrame || webkitRequestAnimationFrame || mozRequestAnimationFrame || oRequestAnimationFrame || msRequestAnimationFrame || function(callback) {
        return setTimeout(callback, 1000 / 60);
      };
    })();
    window.cancelAnimFrame = (function() {
      return cancelAnimationFrame || webkitCancelAnimationFrame || mozCancelAnimationFrame || oCancelAnimationFrame || msCancelAnimationFrame;
    })();
    HTMLElement.prototype.requestFullscreen = (function() {
      if (HTMLElement.prototype.requestFullscreen) {
        return HTMLElement.prototype.requestFullscreen;
      } else if (HTMLElement.prototype.mozRequestFullScreen) {
        return HTMLElement.prototype.mozRequestFullScreen;
      } else if (HTMLElement.prototype.webkitRequestFullscreen) {
        return function() {
          return this.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
        };
      } else if (HTMLElement.prototype.webkitRequestFullScreen) {
        return function() {
          return this.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT);
        };
      }
    })();
    document.exitFullscreen = (function() {
      return document.exitFullscreen || document.mozCancelFullScreen || document.webkitExitFullScreen || document.webkitCancelFullScreen;
    })();
    document.isFullScreen = function() {
      return (document.fullScreenElement != null) || (document.mozFullScreenElement != null) || document.mozIsFullScreen || (document.webkitFullScreenElement != null) || document.webkitIsFullScreen;
    };
    return window.fullscreenchange = (function() {
      var body;

      body = document.body;
      if (body.onfullscreenchange != null) {
        return 'fullscreenchange';
      } else if (body.onmozfullscreenchange != null) {
        return 'mozfullscreenchange';
      } else if (body.onwebkitfullscreenchange != null) {
        return 'webkitfullscreenchange';
      } else {
        return null;
      }
    })();
  })();

}).call(this);
