// Generated by CoffeeScript 1.6.3
(function() {
  var messageHandler, update, _chromosomeIndex, _tetris;

  importScripts('tetris.js', '/libraries/underscore.js');

  _tetris = _chromosomeIndex = null;

  update = function() {
    if (_tetris.gameOver()) {
      self.postMessage({
        func: 'complete',
        score: _tetris.score,
        index: _chromosomeIndex
      });
      return self.close();
    } else {
      _tetris.makeMove();
      return self.postMessage({
        func: 'move',
        tetris: _tetris,
        index: _chromosomeIndex
      });
    }
  };

  messageHandler = function(e) {
    var chromosome, chromosomeIndex, func, index, workerIndex, _ref;
    func = e.data.func;
    switch (func) {
      case 'evaluateFitness':
        _ref = e.data, chromosome = _ref.chromosome, index = _ref.index;
        workerIndex = index.workerIndex, chromosomeIndex = index.chromosomeIndex;
        _tetris = new TetrisAI(chromosome.genes);
        _chromosomeIndex = chromosomeIndex;
        return update();
      case 'update':
        return update();
    }
  };

  self.addEventListener('message', messageHandler, false);

}).call(this);
