// Generated by CoffeeScript 1.6.2
(function() {
  (typeof exports !== "undefined" && exports !== null ? exports : this).Twitter = (function() {
    var MONTHS, TWEET_PATH, _$twitter, _count, _displayNextTweet, _formatDate, _handleTweets, _tweets;

    MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    TWEET_PATH = 'http://phenomnomnominal.herokuapp.com/getTweets.json?callback=?';
    _$twitter = $('#twitter span');
    _tweets = _count = null;
    _formatDate = function(date) {
      var dateStr, day, hour, meridian, mins, month, year;

      date = new Date(date);
      month = date.getMonth();
      day = date.getDate();
      year = date.getFullYear();
      hour = date.getHours();
      mins = date.getMinutes();
      meridian = hour > 11 ? 'PM' : 'AM';
      hour = hour % 12;
      hour = hour === 0 ? 12 : hour;
      mins = mins < 10 ? '0' + mins : mins;
      return dateStr = "" + MONTHS[month] + " " + day + ", " + year + " at " + hour + ":" + mins + " " + meridian;
    };
    _handleTweets = function(response) {
      _tweets = response.data;
      _displayNextTweet();
      return $(window).resize();
    };
    _displayNextTweet = function() {
      clearInterval(scroll);
      _count = _count === (_tweets.length - 1) || _count === null ? 0 : _count + 1;
      _$twitter.html("<em>></em>" + _tweets[_count].text + " - (" + (_formatDate(_tweets[_count].created_at)) + ")");
      return setTimeout((function() {
        var scroll;

        return scroll = setInterval((function() {
          _$twitter.html("<em>></em>" + (_$twitter.text().slice(3)));
          if (_$twitter.text().length < 3) {
            clearInterval(scroll);
            return _displayNextTweet();
          }
        }), 300);
      }), 1000);
    };
    return {
      init: function() {
        return $.getJSON(TWEET_PATH, _handleTweets);
      }
    };
  })();

}).call(this);
