// Generated by CoffeeScript 1.6.2
(function() {
  (typeof exports !== "undefined" && exports !== null ? exports : this).UI = (function() {
    var events;

    events = {
      menuOver: function(blockGroup, name) {
        return function(intersected) {
          events.addPointer();
          blockGroup.animate(Animate.POSITION.Z(Blocks.OUT_POSITION));
          blockGroup.on('click', (function(name) {
            return function() {
              return Routing.go(name);
            };
          })(name));
          blockGroup.on('mouseout', events.menuOut(blockGroup, name));
          return blockGroup.off('mouseover');
        };
      },
      menuOut: function(blockGroup, name) {
        return function(intersected) {
          if (_.intersection(intersected, blockGroup.get('object')).length === 0) {
            events.removePointer();
            blockGroup.animate(Animate.POSITION.Z(Blocks.IN_POSITION));
            blockGroup.off('click');
            blockGroup.off('mouseout');
            return blockGroup.on('mouseover', events.menuOver(blockGroup, name));
          }
        };
      },
      addPointer: function() {
        return $(document.body).addClass('cursor');
      },
      removePointer: function() {
        return $(document.body).removeClass('cursor');
      },
      back: function() {
        return Routing.back();
      },
      initProject: function(e) {
        var projectId, projectName;

        projectId = $(e.target).closest('a').attr('id');
        projectName = projectId.substr(0, projectId.indexOf('-project'));
        return Routing.go("projects/" + projectName);
      },
      toggleFullscreen: function() {
        if (document.isFullScreen()) {
          return document.exitFullscreen();
        } else {
          return document.documentElement.requestFullscreen();
        }
      },
      toggleWireframe: function() {
        return Main.toggleDebug();
      },
      windowResize: function() {
        var height, screenSize, width;

        screenSize = Events.get.screenSize();
        Rendering.setRendererSize(screenSize);
        width = screenSize[0], height = screenSize[1];
        $('main').height(height);
        $('#wrapper').width(width).height(width);
        return $(document.body).css({
          'font-size': (width / 25) * 0.85
        });
      },
      mousemove: function() {
        var x, y, _ref;

        _ref = Events.get.mousePixels(), x = _ref[0], y = _ref[1];
        return Rendering.setLightTarget(new THREE.Vector3(x, 1080 - y, 10));
      }
    };
    return {
      events: events
    };
  })();

}).call(this);
